### ISSUE TITLE
Excellent work! Expect code release！

### ISSUE THREAD

**Issue by pacifinapacific** [samuro95/Self-Supervised-Small-Soccer-Player-Detection-Tracking#1]

**Comment by SilvioGiancola** [comment]
Hi @samuro95, great work! Do you have any plan on releasing your code anytime soon? Thank you for letting us know :)

**Comment by samuro95** [comment]
Hi thank you. Yes I am currently working on it, sorry for the delay. It ll come this month.

**Comment by samuro95** [comment]
Sorry for the delay, i am currently releasing the code
